### ISSUE TITLE
IFPA tournaments command doesn't format as intended

### ISSUE THREAD

**Issue by keyle** [edgiardina/IFPACompanionSlack#1]
The "```" formatting doesn't appear to work

See attachment:

<img width="683" alt="image" src="https://github.com/edgiardina/IFPACompanionSlack/assets/9749/9929081c-a198-4b4e-8485-7ef27de1bb5e">

**Comment by edgiardina** [comment]
Closed; I added a character limit and truncation to make sure the ticks work.
